### ISSUE TITLE
終了画面のSecondViewコンポーネントを作成

### ISSUE THREAD

**Issue by yusei53** [Peach-Tech0927/PeachTech-tutorial#9]
![スクリーンショット 2024-05-15 0 41 11](https://github.com/Peach-Tech0927/PeachTech-tutorial/assets/108526619/372361f2-7b28-4596-bc32-7279d5d1edca)

**Comment by chiikawasaki** [comment]
## PC
![image](https://github.com/Peach-Tech0927/PeachTech-tutorial/assets/166233127/d091197c-ee11-4cf7-912d-8306f7647104)

## SP
![image](https://github.com/Peach-Tech0927/PeachTech-tutorial/assets/166233127/af4e6ade-5b9d-4362-bcfa-6abce8f7a6e2)

@yusei53 
終了画面のSecondViewコンポーネントを作成しました！
お手すきの際にご確認お願いします！
